# Generated by Django 5.2 on 2026-01-15 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(default=2022, on_delete=django.db.models.deletion.PROTECT, to='avaliacoes.responsavel'),
            preserve_default=False,
        ),
    ]
