# Generated by Django 6.0.1 on 2026-02-04 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_remove_professor_ativo_remove_professor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.professor'),
        ),
    ]
