# Generated by Django 5.2 on 2026-01-15 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_responsavel_aluno_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=0, max_digits=1)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.aluno')),
            ],
        ),
    ]
