# Generated by Django 6.0.1 on 2026-01-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_professor_alter_aluno_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='materia',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Português', 'Português'), ('História', 'História'), ('Geografia', 'Geografia'), ('Física', 'Física'), ('Química', 'Química'), ('Biologia', 'Biologia')], max_length=50),
        ),
    ]
