# Generated by Django 6.0.1 on 2026-01-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0005_alter_professor_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
