# Generated by Django 6.0.1 on 2026-01-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0006_professor_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='nota',
            new_name='nota_competencias',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota_conhecimento',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota_engajamento',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota_habilidades',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1),
            preserve_default=False,
        ),
    ]
